export const GET_REPOS_STARTED = 'GET_REPOS_STARTED';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
export const GET_REPOS_ERROR = 'GET_REPOS_ERROR';
export const GET_SESSIONS_FROM_LOCALSTORAGE = 'GET_SESSIONS_FROM_LOCALSTORAGE';
